import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Gem, ShieldCheck, CheckCircle2, AlertTriangle, HelpCircle, Scale, Lock } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { createPageMetadata } from "@/lib/metadata";

export const metadata: Metadata = createPageMetadata(
  "Alternative Investment Funds (AIF) — Category II & III Strategies",
  "Institutional Alternative Investment Funds (AIF) for sophisticated investors. Minimum investment ₹1 Crore as mandated by SEBI. Private equity, venture debt, and hedge strategies.",
  "/investments/aif"
);

const AIF_CATEGORIES = [
  {
    cat: "Category I AIF",
    theme: "Social & Economic Priority Sectors",
    focus: "Venture Capital, SME Funds, Social Impact Funds, Infrastructure Funds",
    tenure: "5 to 7 Years (Close-ended)",
    summary: "Funds that invest in start-ups, early-stage ventures, or social infrastructure projects deemed economically vital by the government and SEBI.",
  },
  {
    cat: "Category II AIF",
    theme: "Private Equity & Private Credit",
    focus: "Private Equity Funds, Real Estate Funds, Structured Debt, Special Situations",
    tenure: "3 to 6 Years (Close-ended)",
    summary: "Funds that do not undertake leverage other than to meet day-to-day operational requirements. Primarily unlisted equity, mezzanine finance, and secured private debt.",
  },
  {
    cat: "Category III AIF",
    theme: "Hedge & Tactical Absolute Return",
    focus: "Long-Short Equity Funds, Commodity Arbitrage, Quantitative Alpha, Derivatives",
    tenure: "Open-ended or Close-ended (1–3 Years)",
    summary: "Funds that employ complex trading and derivative strategies including long-short equity and leverage to generate absolute returns regardless of market direction.",
  },
];

const FAQS = [
  {
    q: "What is the minimum regulatory investment for an AIF in India?",
    a: "Under SEBI (Alternative Investment Funds) Regulations, 2012, the statutory minimum investment ticket for an investor in an AIF is ₹1 Crore (or ₹25 Lakhs for employees/directors of the AIF manager).",
  },
  {
    q: "How does AIF taxation work in India?",
    a: "Category I and II AIFs enjoy tax pass-through status: income generated by the fund is taxed directly in the hands of the investor as if they made the investment directly. Category III AIFs are taxed at the investment fund level at the maximum marginal rate (MMR).",
  },
  {
    q: "What is capital commitment and drawdown in AIFs?",
    a: "In most Category I and II AIFs, you commit capital upfront (e.g. ₹1 Crore) which is not drawn all at once. The fund manager issues 'capital calls' over a 2 to 3-year commitment period as viable private deals are identified and executed.",
  },
  {
    q: "Are AIFs liquid?",
    a: "No. Most Category I and II AIFs are strictly close-ended with lock-in tenures ranging from 3 to 7 years. Capital distributions occur as underlying portfolio companies or debt instruments are liquidated.",
  },
];

export default function AIFPage() {
  return (
    <div className="py-12 md:py-20 bg-[var(--color-surface-canvas)] min-h-screen">
      <Container>
        {/* Breadcrumb */}
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-semibold text-[var(--color-text-muted)] mb-8">
          <Link href="/" className="hover:text-[var(--color-text-primary)] transition-colors">Home</Link>
          <span>/</span>
          <Link href="/investments" className="hover:text-[var(--color-text-primary)] transition-colors">Investments</Link>
          <span>/</span>
          <span className="text-[var(--color-text-primary)]">AIF</span>
        </nav>

        {/* Hero */}
        <div className="max-w-4xl mb-14">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-[var(--color-emerald-subtle)] text-[var(--color-secondary)] text-xs font-bold rounded border border-[var(--color-border-strong)] mb-3">
            <Scale size={14} />
            <span>SEBI Statutory Minimum: ₹1 Crore</span>
          </div>
          <h1
            className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-[var(--color-text-primary)] tracking-tight"
            style={{ fontFamily: "var(--font-display)" }}
          >
            Alternative Investment Funds (AIF)
          </h1>
          <p className="text-base sm:text-lg text-[var(--color-text-secondary)] mt-3 leading-relaxed max-w-3xl">
            Institutional pooled investment vehicles for accredited high-net-worth investors seeking uncorrelated
            returns through private equity, structured credit, and long-short absolute return strategies.
          </p>
        </div>

        {/* Categories Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-16">
          {AIF_CATEGORIES.map((cat) => (
            <div key={cat.cat} className="bg-white p-7 rounded-2xl border border-[var(--color-border-subtle)] shadow-[var(--shadow-card)] flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-4">
                  <div className="w-10 h-10 rounded-xl bg-[var(--color-primary)] text-white flex items-center justify-center">
                    <Gem size={18} />
                  </div>
                  <span className="text-[10px] font-bold text-[var(--color-primary)] bg-[var(--color-surface-canvas)] px-2.5 py-1 rounded border border-[var(--color-border-subtle)]">
                    {cat.tenure}
                  </span>
                </div>

                <h3 className="text-lg font-bold text-[var(--color-text-primary)] mb-1" style={{ fontFamily: "var(--font-heading)" }}>
                  {cat.cat}
                </h3>
                <span className="text-xs font-semibold text-[var(--color-secondary)] block mb-3">
                  {cat.theme}
                </span>

                <p className="text-xs text-[var(--color-text-muted)] leading-relaxed mb-4">
                  {cat.summary}
                </p>

                <div className="p-3 bg-[var(--color-surface-low)] rounded-xl border border-[var(--color-border-subtle)] text-[11px] text-[var(--color-text-secondary)] mb-4">
                  <strong>Focus:</strong> {cat.focus}
                </div>
              </div>

              <div className="pt-3 border-t border-[var(--color-border-subtle)]">
                <span className="text-xs font-bold text-[var(--color-primary)] inline-flex items-center gap-1">
                  Private Placement Memorandum (PPM) Basis
                </span>
              </div>
            </div>
          ))}
        </div>

        {/* VISUAL 1: The AIF Investment Lifecycle */}
        <div className="bg-white rounded-2xl p-7 md:p-8 border border-[var(--color-border-subtle)] shadow-[var(--shadow-card)] mb-16">
          <div className="max-w-2xl mb-6">
            <SectionLabel>Institutional Mechanism</SectionLabel>
            <h3 className="text-xl font-bold text-[var(--color-text-primary)] mt-1" style={{ fontFamily: "var(--font-heading)" }}>
              The 4-Stage AIF Capital Lifecycle
            </h3>
            <p className="text-xs text-[var(--color-text-muted)] mt-1">
              Unlike open-ended mutual funds, Alternative Investment Funds operate on close-ended commitment architectures.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              {
                stage: "01",
                title: "Capital Commitment",
                timing: "Day 1 (Legal Agreement)",
                summary: "Investor executes Contribution Agreement committing minimum ₹1 Crore statutory allocation. Zero immediate 100% debit.",
                badge: "Commitment",
              },
              {
                stage: "02",
                title: "Staged Drawdowns",
                timing: "Years 1 – 3 (Call Period)",
                summary: "Fund Manager issues formal Capital Calls (typically 15%–25% tranches) as viable private assets or debt deals are approved.",
                badge: "Deployment",
              },
              {
                stage: "03",
                title: "Active Asset Portfolio",
                timing: "Years 3 – 5 (Value Add)",
                summary: "Capital is deployed into underlying private enterprises, real estate debt, or long-short hedging strategies generating portfolio yield.",
                badge: "Holding",
              },
              {
                stage: "04",
                title: "Harvest & Realization",
                timing: "Years 5 – 7 (Distributions)",
                summary: "Orderly liquidation, strategic buybacks, or secondary exits. Return of invested capital followed by profit sharing above hurdle.",
                badge: "Distributions",
              },
            ].map((cycle) => (
              <div key={cycle.stage} className="p-5 rounded-xl bg-[var(--color-surface-low)] border border-[var(--color-border-subtle)] flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-mono text-[10px] font-bold text-[var(--color-secondary)]">STAGE {cycle.stage}</span>
                    <span className="text-[10px] font-bold text-[var(--color-text-muted)] bg-white px-2 py-0.5 rounded border border-[var(--color-border-subtle)]">
                      {cycle.badge}
                    </span>
                  </div>
                  <h4 className="text-sm font-bold text-[var(--color-text-primary)] mb-1" style={{ fontFamily: "var(--font-heading)" }}>
                    {cycle.title}
                  </h4>
                  <span className="text-[11px] font-semibold text-[var(--color-secondary)] block mb-3">{cycle.timing}</span>
                  <p className="text-xs text-[var(--color-text-muted)] leading-relaxed mb-3">
                    {cycle.summary}
                  </p>
                </div>
                <div className="w-full h-1 bg-slate-200 rounded-full overflow-hidden">
                  <div className="h-full bg-[var(--color-secondary)]" style={{ width: `${Number(cycle.stage) * 25}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Suitability & Risks */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
          <div className="bg-white p-7 rounded-2xl border border-[var(--color-border-subtle)] shadow-[var(--shadow-card)]">
            <h4 className="text-sm font-bold text-[var(--color-text-primary)] flex items-center gap-2 mb-4">
              <CheckCircle2 size={16} className="text-[var(--color-secondary)]" />
              Eligibility & Suitability
            </h4>
            <ul className="flex flex-col gap-2.5 text-xs text-[var(--color-text-secondary)] leading-relaxed">
              <li>• Qualified accredited investors and family offices capable of deploying ₹1 Crore+ minimum.</li>
              <li>• Sophisticated portfolios looking for non-public market diversification and unlisted equity upside.</li>
              <li>• Investors with patient capital who do not require liquidity for 3 to 7 years.</li>
              <li>• Institutional balance sheets seeking private debt yields secured by corporate collateral.</li>
            </ul>
          </div>

          <div className="bg-white p-7 rounded-2xl border border-[var(--color-border-subtle)] shadow-[var(--shadow-card)]">
            <h4 className="text-sm font-bold text-[var(--color-text-primary)] flex items-center gap-2 mb-4">
              <AlertTriangle size={16} className="text-[var(--color-tertiary)]" />
              Critical Risk Factors
            </h4>
            <ul className="flex flex-col gap-2.5 text-xs text-[var(--color-text-muted)] leading-relaxed">
              <li>• <strong>High Illiquidity:</strong> Units cannot be easily redeemed or traded before fund winding up.</li>
              <li>• <strong>Execution & Deal Risk:</strong> Private equity outcomes depend heavily on manager execution.</li>
              <li>• <strong>Drawdown Uncertainty:</strong> Capital calls occur sporadically over several calendar years.</li>
              <li>• <strong>No Capital Protection:</strong> Alternative strategies carry substantial risk of principal impairment.</li>
            </ul>
          </div>
        </div>

        {/* FAQs */}
        <div className="mb-16">
          <h3 className="text-xl font-bold text-[var(--color-text-primary)] mb-6" style={{ fontFamily: "var(--font-heading)" }}>
            Frequently Asked Questions on AIFs
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {FAQS.map((faq) => (
              <div key={faq.q} className="p-5 bg-white rounded-xl border border-[var(--color-border-subtle)] shadow-[var(--shadow-card)]">
                <div className="flex items-start gap-2 mb-2">
                  <HelpCircle size={16} className="text-[var(--color-primary)] shrink-0 mt-0.5" />
                  <h4 className="text-sm font-bold text-[var(--color-text-primary)] leading-snug">{faq.q}</h4>
                </div>
                <p className="text-xs text-[var(--color-text-muted)] leading-relaxed pl-6">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="bg-[var(--color-primary)] text-white rounded-2xl p-8 md:p-10 flex flex-col md:flex-row items-center justify-between gap-6 shadow-xl mb-12">
          <div className="max-w-xl">
            <span className="text-xs font-bold uppercase tracking-widest text-[var(--color-secondary-fixed)] block mb-1">
              Institutional Alternatives Desk
            </span>
            <h3 className="text-2xl font-bold text-white tracking-tight" style={{ fontFamily: "var(--font-heading)" }}>
              Request Private Placement Memorandums (PPM)
            </h3>
            <p className="text-xs text-white/70 mt-2 leading-relaxed">
              Inquire about current Category II and III fund availability with founder Panchanan Kumar.
            </p>
          </div>
          <Link
            href="/contact"
            className="px-7 py-3.5 bg-[var(--color-secondary)] hover:bg-[var(--color-secondary-700)] text-white text-xs font-bold rounded-xl text-center shrink-0 shadow-md transition-colors inline-flex items-center gap-2"
          >
            <span>Inquire About AIF</span>
            <ArrowRight size={14} />
          </Link>
        </div>

        {/* Statutory Compliance Footer */}
        <div className="p-4 rounded-xl bg-white border border-[var(--color-border-subtle)] flex items-start gap-3 text-xs text-[var(--color-text-muted)]">
          <ShieldCheck size={18} className="text-[var(--color-text-muted)] shrink-0 mt-0.5" />
          <p className="leading-relaxed">
            <strong>Statutory Disclosure:</strong> Alternative Investment Funds are high-risk vehicles intended strictly for sophisticated,
            accredited investors capable of evaluating private placement memorandums. Past performance of previous funds does not guarantee
            future outcomes. FINREV SOLUTIONS distributes third-party SEBI-registered AIF products.
          </p>
        </div>
      </Container>
    </div>
  );
}
