"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  ArrowRight,
  Check,
  Copy,
  Info,
  Phone,
  Printer,
  RotateCcw,
  ShieldAlert,
  Sparkles,
} from "lucide-react";
import { CONTACT } from "@/lib/constants";

// ------------------------------------------------------------
// Educational Primer Panel
// ------------------------------------------------------------
interface EducationalPrimerProps {
  title: string;
  paragraphs: string[];
  takeaways?: string[];
}

export function EducationalPrimer({
  title,
  paragraphs,
  takeaways,
}: EducationalPrimerProps) {
  return (
    <div className="bg-white rounded-2xl border border-[var(--color-border-subtle)] p-6 md:p-8 shadow-[var(--shadow-card)] mb-10">
      <div className="flex items-center gap-2.5 pb-4 mb-4 border-b border-[var(--color-border-subtle)]">
        <Sparkles size={18} className="text-[var(--color-secondary)]" />
        <h3 className="text-base font-bold text-[var(--color-text-primary)]">
          {title}
        </h3>
      </div>
      <div className="space-y-3.5 text-sm text-[var(--color-text-secondary)] leading-relaxed">
        {paragraphs.map((p, idx) => (
          <p key={idx}>{p}</p>
        ))}
      </div>
      {takeaways && takeaways.length > 0 && (
        <div className="mt-6 pt-5 border-t border-[var(--color-border-subtle)]">
          <span className="text-xs font-bold uppercase tracking-wider text-[var(--color-text-primary)] block mb-3">
            Key Strategic Takeaways
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {takeaways.map((item, idx) => (
              <div
                key={idx}
                className="flex items-start gap-2 text-xs text-[var(--color-text-secondary)] bg-[var(--color-surface-canvas)] p-3 rounded-xl border border-[var(--color-border-subtle)]"
              >
                <div className="w-1.5 h-1.5 rounded-full bg-[var(--color-secondary)] mt-1.5 shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ------------------------------------------------------------
// Assumptions & Methodology Panel
// ------------------------------------------------------------
interface AssumptionsPanelProps {
  assumptions: string[];
}

export function AssumptionsPanel({ assumptions }: AssumptionsPanelProps) {
  return (
    <div className="bg-[var(--color-surface-low)] rounded-2xl border border-[var(--color-border-subtle)] p-6 mb-10">
      <div className="flex items-center gap-2 mb-3">
        <Info size={16} className="text-[var(--color-text-muted)]" />
        <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-text-primary)]">
          Model Assumptions & Methodology
        </h4>
      </div>
      <ul className="space-y-2 text-xs text-[var(--color-text-secondary)]">
        {assumptions.map((asm, idx) => (
          <li key={idx} className="flex items-start gap-2">
            <span className="text-[var(--color-text-muted)] shrink-0">•</span>
            <span>{asm}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// ------------------------------------------------------------
// Statutory Regulatory Disclaimer Panel (SEBI/AMFI)
// ------------------------------------------------------------
interface DisclaimerPanelProps {
  customText?: string;
}

export function DisclaimerPanel({ customText }: DisclaimerPanelProps) {
  return (
    <div className="p-4 rounded-xl bg-white border border-[var(--color-border-subtle)] flex items-start gap-3 text-xs text-[var(--color-text-muted)] mb-10">
      <ShieldAlert size={18} className="text-[var(--color-text-muted)] shrink-0 mt-0.5" />
      <p className="leading-relaxed">
        <strong>Statutory Disclosure & Caveats:</strong> Mutual fund investments and securities markets are subject
        to market risks. Read all scheme-related documents carefully before investing.{" "}
        {customText ||
          "Calculations generated by this tool are purely mathematical simulations based on user-supplied inputs and assumed hypothetical rates of return. They do not represent past performance, future returns, or guaranteed outcomes of any financial product or scheme."}
      </p>
    </div>
  );
}

// ------------------------------------------------------------
// Lead CTA Box (Speak with Panchanan Kumar)
// ------------------------------------------------------------
interface CalculatorCTAProps {
  primaryActionText?: string;
  primaryActionHref?: string;
}

export function CalculatorCTA({
  primaryActionText = "Execute This Financial Strategy",
  primaryActionHref = "/contact",
}: CalculatorCTAProps) {
  return (
    <div className="pt-4 border-t border-[var(--color-border-subtle)] flex flex-col gap-2.5">
      <Link
        href={primaryActionHref}
        className="w-full py-3.5 bg-[var(--color-secondary)] hover:bg-[var(--color-secondary-700)] text-white text-xs font-bold rounded-xl text-center shadow-md transition-colors flex items-center justify-center gap-2"
      >
        <span>{primaryActionText}</span>
        <ArrowRight size={14} />
      </Link>
      <a
        href={CONTACT.phoneTel}
        className="w-full py-2.5 bg-white border border-[var(--color-border-strong)] hover:bg-[var(--color-surface-low)] text-[var(--color-text-primary)] text-xs font-bold rounded-xl text-center transition-colors flex items-center justify-center gap-2"
      >
        <Phone size={13} />
        <span>Speak with Panchanan Kumar</span>
      </a>
    </div>
  );
}

// ------------------------------------------------------------
// Calculator Utility Actions (Reset, Share, Print)
// ------------------------------------------------------------
interface CalculatorActionsProps {
  onReset: () => void;
}

export function CalculatorActions({ onReset }: CalculatorActionsProps) {
  const [copied, setCopied] = useState(false);

  const handleShare = () => {
    if (typeof window !== "undefined") {
      navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handlePrint = () => {
    if (typeof window !== "undefined") {
      window.print();
    }
  };

  return (
    <div className="flex items-center gap-2 pt-4 border-t border-[var(--color-border-subtle)] text-xs font-semibold text-[var(--color-text-muted)]">
      <button
        type="button"
        onClick={onReset}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--color-border-subtle)] hover:bg-[var(--color-surface-low)] hover:text-[var(--color-text-primary)] transition-colors"
      >
        <RotateCcw size={13} />
        <span>Reset</span>
      </button>

      <button
        type="button"
        onClick={handleShare}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--color-border-subtle)] hover:bg-[var(--color-surface-low)] hover:text-[var(--color-text-primary)] transition-colors"
      >
        {copied ? <Check size={13} className="text-[var(--color-secondary)]" /> : <Copy size={13} />}
        <span>{copied ? "Link Copied!" : "Share"}</span>
      </button>

      <button
        type="button"
        onClick={handlePrint}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--color-border-subtle)] hover:bg-[var(--color-surface-low)] hover:text-[var(--color-text-primary)] transition-colors ml-auto"
      >
        <Printer size={13} />
        <span>Print</span>
      </button>
    </div>
  );
}
